// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP0u-5VF4SSZ7ObkvZdxdNfevgqmiJEE4',
    appId: '1:217690286262:web:99a43abc9b1945081c5e17',
    messagingSenderId: '217690286262',
    projectId: 'crop-guardian-2298d',
    authDomain: 'crop-guardian-2298d.firebaseapp.com',
    storageBucket: 'crop-guardian-2298d.firebasestorage.app',
    measurementId: 'G-L061124RXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKeQCc08LaMKOGqY9mJvIEi_e3K-kDvmU',
    appId: '1:933418454759:android:70a72a093368822b295c42',
    messagingSenderId: '933418454759',
    projectId: 'crop-guardian-9d47a',
    storageBucket: 'crop-guardian-9d47a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSd3ahd0sKm07nkBxA_X598caZaaMzXg',
    appId: '1:933418454759:ios:1fb32f20cfc5f66f295c42',
    messagingSenderId: '933418454759',
    projectId: 'crop-guardian-9d47a',
    storageBucket: 'crop-guardian-9d47a.firebasestorage.app',
    iosClientId: '933418454759-179ir18fc14qve6hkigj5gissrh57dfa.apps.googleusercontent.com',
    iosBundleId: 'com.tejas.cropguardian',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJnqdsUHQaGpsFQi6C7Z5Re1ixGJYPww',
    appId: '1:217690286262:ios:ad801754610164b41c5e17',
    messagingSenderId: '217690286262',
    projectId: 'crop-guardian-2298d',
    storageBucket: 'crop-guardian-2298d.firebasestorage.app',
    iosBundleId: 'com.tejas.cropguardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP0u-5VF4SSZ7ObkvZdxdNfevgqmiJEE4',
    appId: '1:217690286262:web:6e6bc61667f62afe1c5e17',
    messagingSenderId: '217690286262',
    projectId: 'crop-guardian-2298d',
    authDomain: 'crop-guardian-2298d.firebaseapp.com',
    storageBucket: 'crop-guardian-2298d.firebasestorage.app',
    measurementId: 'G-M6N7ZKWWXT',
  );
}
